[package]
name = "crustal"
version = "0.1.0"
authors = ["yellowtides <andi.dicu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
